export default [
  {
    id: 28,
    name: 'Action',
    poster: 'https://image.tmdb.org/t/p/w500/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg',
    top_movie_title: 'Inception',
  },
  {
    id: 12,
    name: 'Adventure',
    poster: 'https://image.tmdb.org/t/p/w500/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg',
    top_movie_title: 'Interstellar',
  },
  {
    id: 16,
    name: 'Animation',
    poster: 'https://image.tmdb.org/t/p/w500/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg',
    top_movie_title: 'Inside Out',
  },
  {
    id: 35,
    name: 'Comedy',
    poster: 'https://image.tmdb.org/t/p/w500/3E53WEZJqP6aM84D8CckXx4pIHw.jpg',
    top_movie_title: 'Deadpool',
  },
  {
    id: 80,
    name: 'Crime',
    poster: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    top_movie_title: 'The Dark Knight',
  },
  {
    id: 99,
    name: 'Documentary',
    poster: 'https://image.tmdb.org/t/p/w500/jntLBq0MLR3hrwKaTQswxACRPMs.jpg',
    top_movie_title: 'Harry Potter 20th Anniversary: Return to Hogwarts',
  },
  {
    id: 18,
    name: 'Drama',
    poster: 'https://image.tmdb.org/t/p/w500/jSziioSwPVrOy9Yow3XhWIBDjq1.jpg',
    top_movie_title: 'Fight Club',
  },
  {
    id: 10751,
    name: 'Family',
    poster: 'https://image.tmdb.org/t/p/w500/mFvoEwSfLqbcWwFsDjQebn9bzFe.jpg',
    top_movie_title: 'Up',
  },
  {
    id: 14,
    name: 'Fantasy',
    poster: 'https://image.tmdb.org/t/p/w500/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg',
    top_movie_title: "Harry Potter and the Philosopher's Stone",
  },
  {
    id: 36,
    name: 'History',
    poster: 'https://image.tmdb.org/t/p/w500/zSqJ1qFq8NXFfi7JeIYMlzyR0dx.jpg',
    top_movie_title: 'The Imitation Game',
  },
  {
    id: 27,
    name: 'Horror',
    poster: 'https://image.tmdb.org/t/p/w500/9E2y5Q7WlCVNEhP5GiVTjhEhx1o.jpg',
    top_movie_title: 'It',
  },
  {
    id: 10402,
    name: 'Music',
    poster: 'https://image.tmdb.org/t/p/w500/6Ryitt95xrO8KXuqRGm1fUuNwqF.jpg',
    top_movie_title: 'Coco',
  },
  {
    id: 9648,
    name: 'Mystery',
    poster: 'https://image.tmdb.org/t/p/w500/nrmXQ0zcZUL8jFLrakWc90IR8z9.jpg',
    top_movie_title: 'Shutter Island',
  },
  {
    id: 10749,
    name: 'Romance',
    poster: 'https://image.tmdb.org/t/p/w500/saHP97rTPS5eLmrLQEcANmKrsFl.jpg',
    top_movie_title: 'Forrest Gump',
  },
  {
    id: 878,
    name: 'Science Fiction',
    poster: 'https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',
    top_movie_title: 'The Avengers',
  },
  {
    id: 10770,
    name: 'TV Movie',
    poster: 'https://image.tmdb.org/t/p/w500/1DGmWZjUJPeKGFRHGCA6VPFUBML.jpg',
    top_movie_title: 'High School Musical',
  },
  {
    id: 53,
    name: 'Thriller',
    poster: 'https://image.tmdb.org/t/p/w500/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
    top_movie_title: 'Pulp Fiction',
  },
  {
    id: 10752,
    name: 'War',
    poster: 'https://image.tmdb.org/t/p/w500/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg',
    top_movie_title: 'Inglourious Basterds',
  },
  {
    id: 37,
    name: 'Western',
    poster: 'https://image.tmdb.org/t/p/w500/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg',
    top_movie_title: 'Django Unchained',
  },
];
